name: complete workflow

on: [push, pull_request]

jobs:
  build-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: whatever
        run: echo ${{ github.event.pull_request.head.sha }}
