name: complete workflow

on: [push, pull_request]

jobs:
  build-push-docker-images:
    strategy:
      matrix:
        component: [core, serving]
    steps:
      - uses: actions/checkout@v2
      - name: whatever
        run: echo {{ github.event.pull_request.head.sha }}
      - name: build image
        run: make build-${{ matrix.component }}-docker REGISTRY=gcr.io/kf-feast VERSION=${GITHUB_SHA}
      - name: push image
        run: make push-${{ matrix.component }}-docker REGISTRY=gcr.io/kf-feast VERSION=${GITHUB_SHA}
