name: complete workflow

on: [push, pull_request]

jobs:
  build-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: whatever
        env:
          GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo
          if [ -n "${GITHUB_PR_SHA}" ]; then
            echo $GITHUB_PR_SHA
          fi