#name: master only tests
#
#
#on:
#  release:
#  push:
#    branches: master
#
#jobs:
#  basic-e2e-tests-docker-compose:
#    runs-on: ubuntu-latest
#    name: basic e2e tests on docker compose
#    steps:
#      - uses: actions/checkout@v2
#      - name: test docker compose
#        run: ./infra/scripts/test-docker-compose.sh
#
#      - name: push feast core dev image
#        run: |
#          if [ ${GITHUB_REF#refs/*/} == "master" ]; then
#            docker tag gcr.io/kf-feast/feast-core:${GITHUB_SHA} gcr.io/kf-feast/feast-core:dev
#            docker push gcr.io/kf-feast/feast-core:dev
#          fi
#
#
##          # Build and push semver tagged commits
##          rx='^([0-9]+\.){0,2}(\*|[0-9]+)$'
##          if [[ ${PULL_BASE_REF:1} =~ $rx ]]; then
##
##          docker tag gcr.io/kf-feast/feast-core:${PULL_BASE_SHA} gcr.io/kf-feast/feast-core:${PULL_BASE_REF:1}
##          docker push gcr.io/kf-feast/feast-core:${PULL_BASE_REF:1}
##
##          docker tag gcr.io/kf-feast/feast-serving:${PULL_BASE_SHA} gcr.io/kf-feast/feast-serving:${PULL_BASE_REF:1}
##          docker push gcr.io/kf-feast/feast-serving:${PULL_BASE_REF:1}
##
##          docker tag gcr.io/kf-feast/feast-jupyter:${PULL_BASE_SHA} gcr.io/kf-feast/feast-jupyter:${PULL_BASE_REF:1}
##          docker push gcr.io/kf-feast/feast-jupyter:${PULL_BASE_REF:1}
##
##          # Also update "latest" image if tagged commit is pushed to stable branch
##          HIGHEST_SEMVER_TAG=$(git tag -l --sort -version:refname | head -n 1)
##          echo "Only push to latest tag if tag is the highest semver version $HIGHEST_SEMVER_TAG"
##
##          if [ "${PULL_BASE_REF:1}" == "${HIGHEST_SEMVER_TAG:1}" ]
##          then
##          docker tag gcr.io/kf-feast/feast-core:${PULL_BASE_SHA} gcr.io/kf-feast/feast-core:latest
##          docker push gcr.io/kf-feast/feast-core:latest
##
##          docker tag gcr.io/kf-feast/feast-serving:${PULL_BASE_SHA} gcr.io/kf-feast/feast-serving:latest
##          docker push gcr.io/kf-feast/feast-serving:latest
##
##          docker tag gcr.io/kf-feast/feast-jupyter:${PULL_BASE_SHA} gcr.io/kf-feast/feast-jupyter:latest
##          docker push gcr.io/kf-feast/feast-jupyter:latest
##          fi
##          fi